### ISSUE TITLE
new Branches

### ISSUE THREAD

**Issue by RockSupport** [balena-os/balena-isg#129]
Could you create new branches
We need update yocto version to kirkstone

**Comment by floion** [comment]
Hi, you can do the update to Kirkstone without creating new branches. You should do the update in the master branch

**Comment by RockSupport** [comment]
New BSP layer,new Kernel,Modify too much. We need balena verify first, It is rigorously tested before they are updated

**Comment by floion** [comment]
Hi, can this issue be closed now?
